### ISSUE TITLE
[Bug] - es_extended - After relog, player are not recognized as dead

### ISSUE THREAD

**Issue by lush0n3** [esx-framework/esx_core#1323]
**Describe the bug**
When player dies and does reconnect, he's not recognized as dead and dead player cannot call for emergency services also can't see respawn/bleedout timer.

**To Reproduce**

Die
Quit game
Connect back to game
Player won't receive option to call for emergency or see timer until respawn.
Debug Info:

**Expected behavior**
Upon connection, the player should appear dead again, but appears lifeless, lying on the ground and without the possibility of calling emergency services, nor the possibility of being revived by another player.

**Screenshots**
![image](https://github.com/esx-framework/esx_core/assets/87586904/84c3c1f9-2689-4881-bab2-df3377d84aec)

**Debug Info (please complete the following information):**
 - OS: Linux
 - FiveM Artifact: 7290
 - ESX Version: 1.10.5
 - Multicharacters
 - illenium-apperance

**Comment by Gellipapa** [comment]
Hi! We fixed this issue 1.10.4. I deleted my core and copy and paste 1.10.5 and works perfectly. 
![image](https://github.com/esx-framework/esx_core/assets/22717950/34f04d45-714d-4475-9973-8e1ab4163af9)

**Comment by lush0n3** [comment]
I will update again, I am on the latest version of all repositories and it is not working correctly, do you use multicharacters?

**Comment by lush0n3** [comment]
> Previously this was a bug, it was recommended that you re-download and copy 1.10.5 and it should work.

I updated everything and it still doesn't work, like I said before I'm using multicharacters.
![image](https://github.com/esx-framework/esx_core/assets/87586904/25b992e5-4830-4bb6-b321-2b347fa283fc)

**Comment by lush0n3** [comment]
Video Showcase: https://streamable.com/bcllz3

**Comment by Gellipapa** [comment]
Hi! @lush0n3 Thank you for your response. I will try again setup in txadmin.

**Comment by Gellipapa** [comment]
@lush0n3 
I did a complete new installation with multicharacter and it works for me. Are you sure you are using the official esx_ambulancejob? 

Previously this was indeed a bug but it has been fixed and I can't cause the problem.

Is there something wrong with the client or server console?
 
Is the state of death saved in a database?

**Comment by lush0n3** [comment]
Yes, I am using the official version with the latest changes. 

https://github.com/esx-framework/esx_ambulancejob

I did a review of all the scripts that interact with access and everything is correct.

**Comment by lush0n3** [comment]
@Gellipapa 
I found the problem or at least what causes it.

If you switch with forcelog or log out and open the game between a dead and a living character the problem occurs, or when you log out dead, at least that's what's happening to me.

I don't know if this is associated with the "isDeadState" function

But do what I say, log out with a dead player, then log in with a live player, log out and log back in with the dead one, at least that's how I get the error.

Thanks in advance for your time

**Comment by Gellipapa** [comment]
@lush0n3 Hi! I tested your descriptions, and it's works. 

Video: https://streamable.com/2ge2lx

I don't quite understand why it doesn't work for you, we need to do more testing.
There is a bug that forcelog does not reset ambulancejob timer but that is another bug.

**Comment by lush0n3** [comment]
Hello again, I found out which script is giving the problem.

illenium-appearance: https://github.com/iLLeniumStudios/illenium-appearance

Apparently it triggers an event after all the ESX events and revives the player, leaving them dead but unable to send dispatch.

I don't know if the same thing will happen when using fivem-appearance but I will continue testing and looking for the problem.

**Comment by lush0n3** [comment]
> @lush0n3 Hi! I tested your descriptions, and it's works.
> 
> Video: https://streamable.com/2ge2lx
> 
> I don't quite understand why it doesn't work for you, we need to do more testing. There is a bug that forcelog does not reset ambulancejob timer but that is another bug.

Hello again, I found out which script is giving the problem.

illenium-appearance: https://github.com/iLLeniumStudios/illenium-appearance

Apparently it triggers an event after all the ESX events and revives the player, leaving them dead but unable to send dispatch.

I don't know if the same thing will happen when using fivem-appearance but I will continue testing and looking for the problem.

**Comment by horvathg-novin** [comment]
@lush0n3 Hi! Thanks, let us know what you find out and we'll see how we can help you fix the illenium if that is indeed the problem.

**Comment by Gellipapa** [comment]
@lush0n3 Hi! Thanks, let us know what you find out and we'll see how we can help you fix the illenium if that is indeed the problem.

**Comment by Minimalistic09** [comment]
Hello i have the same issue, when i relog i dying i use the last version of esx legacy
any know how fix it?

**Comment by Gellipapa** [comment]
@Minimalistic09 Hi! Do you use illenium appearance?

**Comment by lush0n3** [comment]
> Hello i have the same issue, when i relog i dying i use the last version of esx legacy any know how fix it?

I tried a lot of things and none of them worked, so I went back to the previous.

I mean, I didn't update the file -> \es_extended\client\main.lua (1.10.4)

**Comment by cipherbullet** [comment]
I also have this issue, fresh installation of es_extended and disables multicharacter and identity
