### ISSUE TITLE
[Bug] - ESX - Death state

### ISSUE THREAD

**Issue by iSentrie** [esx-framework/esx_core#1602]
**Describe the bug**
When `esx_multicharacter` is not in use, the death state for players is not recognized when they die for the first time. The death system only begins to function correctly after the player has been revived using `/revive`. From the second death onward, the death state works as intended.

**To Reproduce**
1. Start the server without the `esx_multicharacter` resource.
2. Join the server and die for the first time.
3. Death state should not be triggered properly.
4. Use `/revive me`
5. Die a second time, the death state now works as intended.

**Expected behavior**
The death state should be recognized correctly on the first death, even without the `esx_multicharacter` resource.

**Debug Info:**
 - OS: Windows
 - FiveM Artifact: 12255, 12508 (tested on both)
 - ESX Version: v1.12.3

**Additional context**
This started to happen yesterday, right after FiveM CnL downtime, weird coincidence? Probably yes. Issue seems to occur due to failed initialization after player spawn when `esx_multicharacter`... Still unsure about exact cause of this problem.

**Comment by Tiziukas** [comment]
I believe this issue was already fixed in a PR by @Kenshiin13

**Comment by iSentrie** [comment]
That indeed seems to fix this issue probably should be pushed asap for everyone?

https://github.com/esx-framework/esx_core/blob/11d3c72b2b883f624077cadcba684048ed1c54c1/%5Bcore%5D/es_extended/client/modules/death.lua#L64-L65

**Comment by iSentrie** [comment]
Fixed in v1.12.4

**Comment by Craiin** [comment]
We are still experiencing this with v1.12.4 and multichar. You basically spawn as michael ped for 2 seconds full of blood and need to be revived in order to use all functions correclty. 

BUT not happening to all users :/
