### ISSUE TITLE
[Bug] - esx_extended - problem with kill, player death and interaction

### ISSUE THREAD

**Issue by karolmystore** [esx-framework/esx_core#1621]
**Describe the bug**
When a player dies for the first time, he does not see a counter, he is not considered dead, only after using the “revive” command and dying again does the animation and death screen appear. In addition, before the player dies and is healed again, there is a problem with interaction - the error “Tried to spawn vehicle on the client but the position is too far away (Out of onesync range)”, it displays when it wants a car (driving school) to appear in the distance of the player. Only after the player is killed and healed, the error stops and everything works correctly. I have the impression that the server does not see the live player after joining the server, only after killing and reviving the player everything works correctly.

I've been going through this problem for several hours and in older versions of es_extended e.g.: 1.10.7 after completely removing lines 21-23 the problem completely disappears and everything works correctly when joining the server and the first death. In the latest version after removing these lines the problem still occurs so please help. 

I did not make any changes in the script, it was tested on wasabi_ambulance as well as on esx_ambulancejob and the exact same problem occurs

    while not DoesEntityExist(ESX.PlayerData.ped) do
        Wait(20)
    end

from es_extended/client/main.lua

**To Reproduce**
1. Connect to game
2. The player will not be given the option to call for help or see a timer until revival after death.

**Debug Info (please complete the following information):**
 - OS: Linux
 -  FiveM Artifact: 13068
 - ESX Version: 1.12.4 Latest
 - Multichar
 
**Video - record of the problem**
https://streamable.com/g07fa6

**Comment by FBFezz** [comment]
Fixed in Dev Branch

**Comment by karolmystore** [comment]
where exactly can i find this current patch? thank you for your help

**Comment by iSentrie** [comment]
its fixed in 1.12.4 https://github.com/esx-framework/esx_core/commit/16437408b4b66b90498e7cfe74cf17ccd1c15168

**Comment by karolmystore** [comment]
I have this version 1.12.4 and the problem still occurs despite the fix :/.

**Comment by iSentrie** [comment]
> I have this version 1.12.4 and the problem still occurs despite the fix :/.

check manually if this is there https://github.com/esx-framework/esx_core/commit/16437408b4b66b90498e7cfe74cf17ccd1c15168

**Comment by karolmystore** [comment]
yes it is and there is still a problem

**Comment by karolmystore** [comment]
This problem continues to occur. Could someone please check it out?

**Comment by Kenshiin13** [comment]
@karolmystore Have you also updated your esx_ambulancejob?

**Comment by karolmystore** [comment]
@Kenshiin13 Yes, I updated to the latest version and the problem continues. With the wasabi_ambulance script there is also a problem so it seems to me that it is not dependent on the script for player revival

**Comment by iSentrie** [comment]
I'm pretty sure, you just failed to update or you are running a different fork instead.

**Comment by iSentrie** [comment]
> [@iSentrie](https://github.com/iSentrie) hmm and is it possible that I am missing a script? Could the database also have an effect on this?

framework only
